### PR TITLE
created nws table CRUD file

### PR DESCRIPTION
**Pull request by lindaspellman**
Hello, I created the CRUD file for the new_window_screen table. Have I done the UPDATE part correctly? Also, are there any other issues I missed?

### CODE REVIEW

**Review by NicholasBoss — CHANGES_REQUESTED** [review]
The width and heigh inch columns should be updated in one UPDATE statement. Add a comma after the first %s after width_inch and add the height_inch = %s afterward. You'll have three variables to enter with this approach.

**Comment by lindaspellman** [comment]
Thanks! I'm going to push my changes now.

**Review by NicholasBoss — CHANGES_REQUESTED** [review]
Replace the AND with a comma in the update function.

**Comment by lindaspellman** [comment]
Thank you. I have fixed it and pushed.

**Review by NicholasBoss — APPROVED** [review]
Nice work! Thanks!

**Pull request merged**
